### ISSUE TITLE
Adding prometheus-net to my project adds over 100 dependent files

### ISSUE THREAD

**Issue by godefroi** [prometheus-net/prometheus-net#72]
I have a .NET 4.6.1 project (class library) that I had previously used with the 1.x version of prometheus-net. When I updated to the 2.x prerelease, over 100 dependent files are added to the project output.

My project doesn't itself target .NET Standard, it targets the .NET Framework.

**Comment by sandersaares** [comment]
Thank you for the report! This is indeed undesirable.

I have published new preview packages containing the fix. They should show up in the NuGet feed shortly with the version string `2.0.0-pre-003009-4e26344`.

**Comment by godefroi** [comment]
I have updated to the version you referenced, and I still get all the files. I am not sure, but is it because of how you're packaging the NuGet library? The NuGet package has a lib\netstandard2.0 folder, but not a lib\net40 like I would expect.

**Comment by godefroi** [comment]
@sandersaares I'm not sure you get notified if it's closed?

**Comment by sandersaares** [comment]
I do get notified even if closed but no worries - ping by name is always safer!

I interpreted the issue as "many NuGet packages are installed into my project as dependencies after installing prometheus-net". Perhaps I read too far into the meaning.

Such NuGet dependencies used to be necessary for .NET SDK/packaging reasons but it appears with with .NET Standard 2.0 they can be eliminated. This is what the commit linked to this issue fixed.

However, as far as I know, the files themselves existing is actually correct - libraries that target .NET Standard will need to target the .NET Standard API contracts which will need to bring in some DLLs for reasons of .NET SDKs/packaging that I have never found a satisfactory explanation for. The reality as I understand it is that the same NuGet packages (or at least some of them) still get installed, they just do not pollute the project's NuGet packages list - the SDK simply installs them silently at runtime when it sees that you are installing a .NET Standard library.

I have seen some rumors that Microsoft plans to fix this with .NET Framework 4.7.2 but only time will tell. At the moment, I believe this is the normal state of things.

**Comment by godefroi** [comment]
So do I need to deploy all of these with my library? Libraries like System.Threading.dll and System.Drawing.Primitives.dll?

**Comment by sandersaares** [comment]
If your library itself is delivered via NuGet, all you need to do is reference prometheus-net in your library's dependencies list and the .NET SDK will automatically ensure that any necessary .NET Standard contract libraries are also present when your library is installed.

If your library is delivered in via some other mechanism (such as direct file copy) then I would suggest still installing prometheus-net via NuGet in ordrer to ensure correct behavior during installation of dependencies.
